/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenersRouteImport } from './routes/screeners'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as FantasyRouteImport } from './routes/fantasy'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BankRouteImport } from './routes/bank'
import { Route as IndexRouteImport } from './routes/index'

const ScreenersRoute = ScreenersRouteImport.update({
  id: '/screeners',
  path: '/screeners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyRoute = FantasyRouteImport.update({
  id: '/fantasy',
  path: '/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/blog': typeof BlogRoute
  '/fantasy': typeof FantasyRoute
  '/invest': typeof InvestRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/screeners': typeof ScreenersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/blog': typeof BlogRoute
  '/fantasy': typeof FantasyRoute
  '/invest': typeof InvestRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/screeners': typeof ScreenersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/blog': typeof BlogRoute
  '/fantasy': typeof FantasyRoute
  '/invest': typeof InvestRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/screeners': typeof ScreenersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank'
    | '/blog'
    | '/fantasy'
    | '/invest'
    | '/markets'
    | '/news'
    | '/portfolio'
    | '/profile'
    | '/screeners'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank'
    | '/blog'
    | '/fantasy'
    | '/invest'
    | '/markets'
    | '/news'
    | '/portfolio'
    | '/profile'
    | '/screeners'
  id:
    | '__root__'
    | '/'
    | '/bank'
    | '/blog'
    | '/fantasy'
    | '/invest'
    | '/markets'
    | '/news'
    | '/portfolio'
    | '/profile'
    | '/screeners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRoute
  BlogRoute: typeof BlogRoute
  FantasyRoute: typeof FantasyRoute
  InvestRoute: typeof InvestRoute
  MarketsRoute: typeof MarketsRoute
  NewsRoute: typeof NewsRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  ScreenersRoute: typeof ScreenersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screeners': {
      id: '/screeners'
      path: '/screeners'
      fullPath: '/screeners'
      preLoaderRoute: typeof ScreenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy': {
      id: '/fantasy'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRoute,
  BlogRoute: BlogRoute,
  FantasyRoute: FantasyRoute,
  InvestRoute: InvestRoute,
  MarketsRoute: MarketsRoute,
  NewsRoute: NewsRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  ScreenersRoute: ScreenersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
